database:
  # NOTE: By design, this setting prevents the SQLITE_DATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  #   database: "_env:SQLITE_DATABASE:veche_test.sqlite3"
  database: veche_test.sqlite3

database-migrate: true

auth-dummy-login: true

stellar-horizon-url: http://localhost:9999
